-- CASE 1
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS 
WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)

-- CASE 2
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID, NAME