-- CASE 1
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS 
WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)

-- CASE 2
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS 
LEFT JOIN ANIMAL_INS ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
