-- CASE 1:
WITH TMP AS(
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY 
GROUP BY FLAVOR
)

SELECT TMP.FLAVOR
FROM TMP JOIN FIRST_HALF ON TMP.FLAVOR = FIRST_HALF.FLAVOR
ORDER BY (TMP.TOTAL + FIRST_HALF.TOTAL_ORDER) DESC
LIMIT 3

-- CASE 2
SELECT FLAVOR
FROM(
    (SELECT * FROM FIRST_HALF)
    UNION ALL
    (SELECT * FROM JULY)
)SUB
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3