WITH TMP AS(
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
FROM JULY 
GROUP BY FLAVOR
)

SELECT TMP.FLAVOR
FROM TMP JOIN FIRST_HALF ON TMP.FLAVOR = FIRST_HALF.FLAVOR
ORDER BY (TMP.TOTAL + FIRST_HALF.TOTAL_ORDER) DESC
LIMIT 3