WITH TMP AS(
    SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(30*DAILY_FEE*((100-DISCOUNT_RATE) / 100),0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CAR
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND CAR.CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = '30일 이상'
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    ON CAR.CAR_ID = HISTORY.CAR_ID
    --11월 달에 사용되고 있는 car_id를 제외
    WHERE HISTORY.CAR_ID
    NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
    )
    GROUP BY CAR_ID
)

SELECT * 
FROM TMP
WHERE 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
