SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W'
ORDER BY MEMBER_ID

-- DATE_FORMAT %Y와 %y, %M과 %m, %D와 %d는 다르다.
-- ORDER BY (컬럼명) ASC - 오름차순, DESC - 내림차순