SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER ='W' AND MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC

-- DATE_FORMAT %Y와 %y, %M과 %m, %D와 %d는 다르다.
-- ORDER BY (컬럼명) ASC - 오름차순, DESC - 내림차순