--CASE 1
SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF JOIN ICECREAM_INFO 
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
-- 조인하는 테이블의 ON 절의 조건이 일치하는 결과만 출력
-- 아래와 같이 FROM을 이용하여 여러 테이블을 작성할 수 있으며
-- JOIN ON을 다음과 같이 여러번 사용할 수 있다.
-- FROM TABLE1 JOIN TABLE2 ON TABLE1.X = TABLE2.Y JOIN TABLE3 ON TABLE2.Y = TABLE3.Z

--CASE 2
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR AND 3000 < TOTAL_ORDER AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC