-- CASE 1
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO, REST_REVIEW
WHERE ADDRESS LIKE '서울%' AND REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC


-- CASE 2:
SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INFO
JOIN REST_REVIEW RE ON INFO.REST_ID = RE.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC