-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM 
(SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION 
SELECT SALES_DATE, PRODUCT_ID,NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE) SUB
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- Mysql에서는 UNION을 위와 같이 사용하고 sub query의 이름을 지정해줘야한다. 위에서는 sub로 지정해주었음
-- union 사용시 각 컬럼 갯수 및 명칭을 맞춰줘야 한다.
-- UNION은 중복을 제거하고, UNION ALL은 중복을 허용한다. 