SELECT COUNT(*) AS USERS FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND 
AGE BETWEEN 20 AND 29

-- CASE 2
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE DATE_FORMAT(JOINED, '%Y') = 2021 AND (AGE BETWEEN 20 AND 29)