-- CASE 1:
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
ORDER BY TIMESTAMPDIFF(SECOND, INS.DATETIME, OUTS.DATETIME) DESC
LIMIT 2

-- TIMEDIFF의 경우 838:59:59보다 큰 값을 리턴하지 못한다.
-- CASE 2:
SELECT ANIMAL_ID, NAME
FROM (
    SELECT INS.ANIMAL_ID, INS.NAME, TIMESTAMPDIFF(SECOND, INS.DATETIME, OUTS.DATETIME) AS DIFF 
    FROM ANIMAL_INS INS
    JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    ORDER BY DIFF DESC
    )SUB
LIMIT 2