SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME REGEXP 'el' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC
