-- CASE 1: LIKE
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME

-- CASE 2: REGEXP
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME REGEXP 'el' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC
