SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소, 
    CONCAT(LEFT(TLNO,3), '-',MID(TLNO,4,4), '-', RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER USERS
JOIN USED_GOODS_BOARD BOARD 
ON USERS.USER_ID = BOARD.WRITER_ID
GROUP BY USER_ID
HAVING 3 <= COUNT(USER_ID)
ORDER BY USER_ID DESC