SELECT APNT_NO, PT_NAME, AP.PT_NO, AP.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP JOIN DOCTOR DOC
ON AP.MDDR_ID = DOC.DR_ID
JOIN PATIENT PA
ON AP.PT_NO = PA.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
    AND AP.MCDP_CD = 'CS' 
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD