SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT JOIN
    PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO JOIN 
    DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE APPOINTMENT.MCDP_CD = 'CS' 
    AND APPOINTMENT.APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD ASC