SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM USER_INFO, ONLINE_SALE
WHERE USER_INFO.USER_ID = ONLINE_SALE.USER_ID AND GENDER IS NOT NULL
GROUP BY  GENDER, YEAR, MONTH
ORDER BY YEAR, MONTH, GENDER