-- CASE 1
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR ASC

-- BETWEEN A and B 는 A이상 B 이하이다.
-- DATE_FORMAT의 %H는 24시간, %h는 12시간 기준이다.

-- CASE 2:
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19 
ORDER BY HOUR