-- CASE 1
SET @hour = -1;
SELECT (@hour := @hour+1) AS HOUR,
    (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) AS COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23
ORDER BY HOUR

-- CASE 2
WITH RECURSIVE TEMP AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TEMP
    WHERE HOUR < 23
)
SELECT TEMP.HOUR AS HOUR, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM TEMP LEFT JOIN ANIMAL_OUTS
ON TEMP.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR;