SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC