SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK JOIN
AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID JOIN 
BOOK_SALES ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY, AUTHOR_NAME
ORDER BY AUTHOR_ID, CATEGORY DESC
